
$securityPartnerProvider = Get-AzSecurityPartnerProvider -ResourceGroupName securityPartnerProviderRG -Name securityPartnerProvider

Set-AzSecurityPartnerProvider -SecurityPartnerProvider $securityPartnerProvider
