
$GetAzDigitalTwinsEndpoint = Get-AzDigitalTwinsEndpoint -EndpointName youriDigitalTwinEndpoint -ResourceGroupName youritemp -ResourceName youriDigitalTwinsTest

Get-AzDigitalTwinsEndpoint -InputObject $GetAzDigitalTwinsEndpoint
